//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ims.rc
//
#define IDI_IMALG                       103
#define IDD_IMAGE_CONTROL               104
#define IDD_OVERLAY_SETTINGS            107
#define IDR_MENU1                       108
#define IDR_MENU2                       109
#define IDD_DIALOG1                     110
#define IDD_CONTEXT_SETUP               110
#define IDD_IMAGE_OPERATIONS            111
#define IDC_RADIO_YUV                   1002
#define IDC_RADIO_Y                     1003
#define IDC_RADIO_U                     1004
#define IDC_RADIO_V                     1005
#define IDC_RADIO_RED                   1006
#define IDC_RADIO_GREEN                 1007
#define IDC_RADIO_BLUE                  1008
#define IDC_MASK_LIGHT                  1009
#define IDC_MASK_DARK                   1010
#define IDC_MASK_ALL                    1011
#define IDC_MASK_LIGHT_SAT              1012
#define IDC_MASK_DARK_SAT               1013
#define IDC_MASK_ALL_SAT                1014
#define IDC_GRAYSCALE_EDGE_DETECT       1015
#define IDC_GRAYSCALE_EDGE_DETECT2      1016
#define IDC_GRAYSCALE_HORIZ_EDGE        1017
#define IDC_GRAYSCALE_SHARPEN           1017
#define IDC_GRAYSCALE_LAPLACIAN_EDGE    1018
#define IDC_GRAYSCALE_SHARPEN2          1018
#define IDC_GRAYSCALE_LAPLACIAN_EDGE2   1019
#define IDC_RAW_SHARPEN                 1020
#define IDC_RAW_SHARPEN2                1021
#define IDC_GRAYSCALE_SMOOTH            1022
#define IDC_GRAYSCALE_VERT_EDGE         1023
#define IDC_GRAYSCALE_SHEN              1023
#define IDC_GRAYSCALE_RESTORE           1024
#define IDC_THRESHOLD_VALUE             1025
#define IDC_BINARIZE                    1026
#define IDC_BINARY_EDGE_DETECT          1027
#define IDC_BINARY_EDGE_DETECT2         1028
#define IDC_GRAYSCALE_DERICHE           1029
#define IDC_BINARY_OPEN                 1030
#define IDC_BINARY_CLOSE                1031
#define IDC_BINARY_DILATE               1032
#define IDC_BINARY_ERODE                1033
#define IDC_GREYSCALE_ADD               1038
#define IDC_ADD_VALUE                   1039
#define IDC_GREYSCALE_MULTIPLY          1040
#define IDC_MULTIPLY_VALUE              1041
#define IDC_SHOW_OVERLAY                1042
#define IDC_GRAYSCALE_OPEN              1043
#define IDC_GRAYSCALE_OPEN2             1044
#define IDC_GRAYSCALE_CLOSE             1044
#define IDC_IMAGE_OPS_DLG               1045
#define IDC_CLEAR_BLOBS                 1046
#define IDC_OVERLAY_COLOR               1046
#define IDC_BOUNDING_RECT_COLOR         1047
#define IDC_EDGE_COLOR                  1048
#define IDC_RAW_RESTORE                 1049
#define IDC_RAW_SMOOTH                  1050
#define IDC_RAW_PROCESSING              1050
#define IDC_RAW_LIST                    1051
#define IDC_GRAYSCALE_PROCESSING        1052
#define IDC_GRAYSCALE_LIST              1053
#define IDC_BINARY_PROCESSING           1054
#define IDC_BINARY_LIST                 1055
#define IDC_COMBO1                      1057
#define IDC_BACKGROUND_ELIMINATION      1057
#define IDC_EDIT2                       1058
#define IDC_SEGMENTATION_THRESHOLD      1058
#define IDC_INCREASE_CONTRAST           1059
#define IDC_BACKGROUND_ELIMINATION2     1060
#define IDC_SEGMENTATION_THRESHOLD_AUTO 1060
#define IDC_AVAILABLE_LIST              1061
#define IDC_CURRENT_LIST                1062
#define IDC_ADD                         1064
#define IDC_REMOVE                      1065
#define IDC_APPLY                       1065
#define IDC_UP                          1066
#define IDC_USE_DEFAULTS                1066
#define IDC_UP2                         1067
#define IDC_DOWN                        1067
#define IDC_SAVE_ONE                    1067
#define IDC_SAVE_TWO                    1068
#define IDC_SAVE_THREE                  1069
#define IDC_SAVE_FOUR                   1070
#define IDC_LOAD_ONE                    1071
#define IDC_LOAD_TWO                    1072
#define IDC_LOAD_THREE                  1073
#define IDC_LOAD_FOUR                   1074
#define IDC_USE_AUTO_THRESHOLD          1075
#define IDC_USE_ADAPTIVE_THRESHOLD      1076
#define IDC_NEIGHBORHOOD_SIZE           1077
#define IDC_USE_AUTO_THRESHOLD2         1078
#define IDC_EDIT1                       1080
#define IDC_PEN_WIDTH                   1080
#define ID_FILE_EXIT                    40001
#define ID_FILE_LOAD_IMAGE              40002
#define ID_FILE_LOAD_BACKGROUND_IMAGE   40003
#define ID_FILE_CLOSE_IMAGE             40004
#define ID_FILE_CLOSE_BACKGROUND_IMAGE  40005
#define ID_FILE_CLOSE_MASKED_IMAGE      40011
#define ID_FILE_CLOSE_CONVOLVED_IMAGE   40013
#define ID_FILE_CLOSE_BINARIZED_IMAGE   40015
#define ID_ZOOM_1X                      40016
#define ID_ZOOM_1                       40017
#define ID_ZOOM_1_2_X                   40018
#define ID_ZOOM_ONE_HALF_X              40019
#define ID_FILE_CLOSE_ALL               40021
#define ID_LOG_SAVE                     40025
#define ID_LOG_SAVE_AS                  40026
#define ID_LOG_CLOSE                    40027
#define ID_SHOW_LOGWINDOW               40028
#define ID_SHOW_LOG_WINDOW              40029
#define ID_LOG_CLEAR                    40030
#define ID_CLEAR_LOG_WINDOW             40031
#define ID_SAVE_IMAGE                   40032
#define ID_CLOSE                        40033
#define ID_SAVE_SAVE                    40034
#define ID_SAVE_SAVECONVOLVEDIMAGE      40035
#define ID_SAVE_SAVEBINARIZEDIMAGE      40036
#define ID_SAVE_MASKED_IMAGE            40037
#define ID_SAVE_CONVOLVED_IMAGE         40038
#define ID_SAVE_BINARIZED_IMAGE         40039
#define ID_SAVE_GREYSCALE_IMAGE         40040
#define ID_BLOBS_FIND                   40041
#define ID_BLOBS_CLEAR                  40042
#define ID_FILE_SETTINGS                40043
#define ID_TOOLS_SHOWOVERLAYPIXELS      40044
#define ID_TOOLS_SHOWBOUNDINGRECTS      40045
#define ID_TOOLS_SHOWEDGES              40046
#define ID_TOOLS_COLORS                 40047
#define ID_SHOW_FILLEDIMAGE             40055
#define ID_SHOW_IMAGEEDGE               40056
#define ID_OPERATION_CALCULATELOCALMAXIMA 40063
#define ID_TOOLS_SHOWIMAGES             40064
#define ID_FILE_LOAD_BACKGROUND_IMAGE_SMOOTHED 40065

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40066
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
